// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh_6k3XuJ7dP95oH4mZbdM2UrZo4Pj8iM',
    appId: '1:660325826499:web:465e8b1574afb347310776',
    messagingSenderId: '660325826499',
    projectId: 'guardianx-bc5b6',
    authDomain: 'guardianx-bc5b6.firebaseapp.com',
    databaseURL: 'https://guardianx-bc5b6-default-rtdb.firebaseio.com',
    storageBucket: 'guardianx-bc5b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN8KWjQzVqR6fZZEa4CDIpW-FT8TL9TSo',
    appId: '1:660325826499:android:73cc651e0ef51ca4310776',
    messagingSenderId: '660325826499',
    projectId: 'guardianx-bc5b6',
    databaseURL: 'https://guardianx-bc5b6-default-rtdb.firebaseio.com',
    storageBucket: 'guardianx-bc5b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoUsCstREeFyYZ_JU9pUFlLOLsPG2x9-Y',
    appId: '1:660325826499:ios:ce5384fb650f35c5310776',
    messagingSenderId: '660325826499',
    projectId: 'guardianx-bc5b6',
    databaseURL: 'https://guardianx-bc5b6-default-rtdb.firebaseio.com',
    storageBucket: 'guardianx-bc5b6.firebasestorage.app',
    iosClientId: '660325826499-8uj3frndi377gdkgap3ctf1gfsncdpos.apps.googleusercontent.com',
    iosBundleId: 'com.example.guardianx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoUsCstREeFyYZ_JU9pUFlLOLsPG2x9-Y',
    appId: '1:660325826499:ios:ce5384fb650f35c5310776',
    messagingSenderId: '660325826499',
    projectId: 'guardianx-bc5b6',
    databaseURL: 'https://guardianx-bc5b6-default-rtdb.firebaseio.com',
    storageBucket: 'guardianx-bc5b6.firebasestorage.app',
    iosClientId: '660325826499-8uj3frndi377gdkgap3ctf1gfsncdpos.apps.googleusercontent.com',
    iosBundleId: 'com.example.guardianx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh_6k3XuJ7dP95oH4mZbdM2UrZo4Pj8iM',
    appId: '1:660325826499:web:b67f4cf84032649d310776',
    messagingSenderId: '660325826499',
    projectId: 'guardianx-bc5b6',
    authDomain: 'guardianx-bc5b6.firebaseapp.com',
    databaseURL: 'https://guardianx-bc5b6-default-rtdb.firebaseio.com',
    storageBucket: 'guardianx-bc5b6.firebasestorage.app',
  );
}
